/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./components/common/BaseFooter.vue')['default']
    BaseMenu: typeof import('./components/common/BaseMenu.vue')['default']
    DetailList: typeof import('./components/DetailList.vue')['default']
    DonateQrcode: typeof import('./components/DonateQrcode.vue')['default']
    MethodIcon: typeof import('./components/MethodIcon.vue')['default']
    RedirectInfo: typeof import('./components/RedirectInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsorAvatar: typeof import('./components/common/SponsorAvatar.vue')['default']
    SponsorBtn: typeof import('./components/common/SponsorBtn.vue')['default']
    SponsorIntro: typeof import('./components/SponsorIntro.vue')['default']
    SponsorRow: typeof import('./components/SponsorRow.vue')['default']
    TheConfig: typeof import('./components/TheConfig.vue')['default']
  }
}
