/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./components/common/BaseFooter.vue')['default']
    BaseHeader: typeof import('./components/common/BaseHeader.vue')['default']
    BaseMenu: typeof import('./components/common/BaseMenu.vue')['default']
    DetailList: typeof import('./components/DetailList.vue')['default']
    DonateQrcode: typeof import('./components/DonateQrcode.vue')['default']
    ExpenseTable: typeof import('./components/ExpenseTable.vue')['default']
    MethodIcon: typeof import('./components/MethodIcon.vue')['default']
    OtherSponsors: typeof import('./components/OtherSponsors.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsorAvatar: typeof import('./components/common/SponsorAvatar.vue')['default']
    SponsorBtn: typeof import('./components/common/SponsorBtn.vue')['default']
    SponsorIntro: typeof import('./components/SponsorIntro.vue')['default']
    SponsorList: typeof import('./components/SponsorList.vue')['default']
    SponsorRow: typeof import('./components/SponsorRow.vue')['default']
  }
}
