// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./src/components/common/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/common/BaseHeader.vue')['default']
    BaseMenu: typeof import('./src/components/common/BaseMenu.vue')['default']
    DetailList: typeof import('./src/components/DetailList.vue')['default']
    DonateQrcode: typeof import('./src/components/DonateQrcode.vue')['default']
    ExpenseTable: typeof import('./src/components/ExpenseTable.vue')['default']
    ICarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    ICarbonHome: typeof import('virtual:vite-icons/carbon/home')['default']
    ICarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    ICarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    ICarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    ICarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    IRiAlipayLine: typeof import('virtual:vite-icons/ri/alipay-line')['default']
    IRiQqLine: typeof import('virtual:vite-icons/ri/qq-line')['default']
    IRiWechatPayLine: typeof import('virtual:vite-icons/ri/wechat-pay-line')['default']
    MethodIcon: typeof import('./src/components/MethodIcon.vue')['default']
    OtherSponsors: typeof import('./src/components/OtherSponsors.vue')['default']
    SponsorsList: typeof import('./src/components/SponsorsList.vue')['default']
  }
}

export { }
